services:
  nats_proxy:
    image: ${REGISTRY_HOST}/nats-proxy
#    image: ${REGISTRY_HOST}/nats-proxy:dev-${GITHUB_REF_NAME}
    build:
      context: ../src
      additional_contexts:
        docker: ../docker
      dockerfile: ../docker/ruby/Dockerfile
      cache_from:
        - type=gha,scope=natsproxy
      cache_to:
        - type=gha,scope=natsproxy,mode=max

  tests:
    image: ${REGISTRY_HOST}/nats-proxy-tests
    build:
      context: ../src
      additional_contexts:
        docker: ../docker
      dockerfile: ../docker/ruby/Dockerfile
      target: tests
      cache_from:
        - type=gha,scope=natsproxy
      cache_to:
        - type=gha,scope=natsproxy,mode=max
